import { pgTable, text, bigint, numeric, boolean } from "drizzle-orm/pg-core";

export const products = pgTable("products", {
  id: text().primaryKey(),
  title: text(),
  jenis: text(),
  image: text(),
  jumlah: bigint({ mode: "number" }),
  harga_satuan: numeric(),
  harga_promo: numeric(),
  total_jumlah: bigint({ mode: "number" }),
  total_harga: numeric(),
  estimasi_pengiriman: bigint({ mode: "number" }),
  shop_name: text(),
  badge: text(),
  live: boolean(),
  status: text(),
  coin_reward_text: text(),
  variant_label: text(),
  price: text(),
  rating: numeric(),
  rating_count: bigint({ mode: "number" }),
  sold: bigint({ mode: "number" }),
  is_mall: boolean(),
  is_ori: boolean(),
  is_favorite: boolean(),
  coin: text(),
  diskon: text(),
  category: text(),
  description: text(),
  shipping: text(),
  promo: text(),
  created_at: text(),
  kota: text(),
  durasi: text(),
  shop_id: bigint({ mode: "number" }),
  is_trending: boolean(),
  image_url: text().array(),
});

export type Products = typeof products.$inferSelect;
export type InsertProduct = typeof products.$inferInsert;
